fix: replace deprecated function calls to criterion::black_box()
The latest update of the criterion library causes deprecation errors from
clippy:

        error: use of deprecated function `criterion::black_box`

This commit replaces the deprecated criterion::black_box() function calls with
std::hint::black_box().

Signed-off-by: Roger Knecht <rknecht@pm.me>